version: 2
updates:
# Fetch and update latest `npm` packages
- package-ecosystem: npm
  directory: '/'
  schedule:
    interval: daily
    time: '00:00'
    timezone: 'Asia/Tokyo'
  open-pull-requests-limit: 10
  labels:
    - 'Type: Environment'
  commit-message:
    prefix: chore
    include: scope
# Fetch and update latest `github-actions` pkgs
- package-ecosystem: github-actions
  directory: '/'
  schedule:
    interval: daily
    time: '00:00'
    timezone: 'Asia/Tokyo'
  open-pull-requests-limit: 10
  labels:
    - 'Type: Environment'
  commit-message:
    prefix: chore
    include: scope
